name: Bug Report
description: File a report for a bug.
title: "[BUG]: "
labels: ["bug", "needs-investigation"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: input
    id: summary
    attributes:
      label: Summary
      description: Summarize the bug encountered concisely.
      placeholder: 'A brief summary of the bug.'
      required: true

  - type: textarea
    id: current-behaviour
    attributes:
      label: What is the current bug behaviour?
      description: What actually happens?
      placeholder: 'Detail the current behavior of the bug.'
      required: true

  - type: textarea
    id: expected-behaviour
    attributes:
      label: What is the expected correct behaviour?
      description: What you should see instead.
      placeholder: 'Describe the expected behavior.'
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: How one can reproduce the issue - this is very important.
      placeholder: 'Step-by-step instructions on how to reproduce the bug.'
      required: true

  - type: textarea
    id: relevant-logs-screenshots
    attributes:
      label: Relevant logs and/or screenshots
      description: Paste any relevant logs - please use code blocks to format console output, logs, and code.
      placeholder: 'Insert logs or screenshots here.'
      render: markdown

  - type: textarea
    id: possible-fixes
    attributes:
      label: Possible fixes
      description: If you can, link to the line of code that might be responsible for the problem.
      placeholder: 'Suggest any potential fixes for the bug.'
      render: markdown
