name: Refactoring Request
description: Suggest a refactoring improvement.
title: "[REFACTORING]: "
labels: ["backstage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a refactoring improvement! Please fill out the following form to help us understand your proposal.

  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Briefly describe what part of the code base needs to be refactored.
      placeholder: 'A brief summary of the refactoring needed.'
      required: true

  - type: textarea
    id: improvements
    attributes:
      label: Improvements
      description: Explain the benefits of refactoring this code.
      placeholder: 'Detail the improvements expected from this refactoring.'
      required: true

  - type: textarea
    id: risks
    attributes:
      label: Risks
      description: List features that can break because of this refactoring and how you intend to address them.
      placeholder: 'Identify any potential risks and your plan to mitigate them.'
      required: true

  - type: textarea
    id: involved-components
    attributes:
      label: Involved Components
      description: List files or directories that will be changed by the refactoring.
      placeholder: 'Specify the components that will be affected.'
      required: true

  - type: textarea
    id: intended-side-effects
    attributes:
      label: "Optional: Intended Side Effects"
      description: If the refactoring involves changes apart from the main improvements, list them here.
      placeholder: 'List any additional side effects or improvements.'
      required: false

  - type: textarea
    id: missing-test-coverage
    attributes:
      label: "Optional: Missing Test Coverage"
      description: List any tests that need to be written or adjusted.
      placeholder: 'Detail the missing test coverage related to this refactoring.'
      required: false

